### ISSUE TITLE
Error importing /data/json/mapgen/campsite.json

### ISSUE THREAD

**Issue by snipercup** [solerante/tiled-cdda-map-extension#49]
I clicked file->Import cdda map
Entered my project dir and the json file ```/home/user/Documents/GitHub/Cataclysm-DDA-1/data/json/mapgen/campsite.json```

Got this error
```
TypeError: Cannot read property 'rows' of undefined
Stack traceback:
  constructor@file:///home/user/.config/tiled/extensions/CDDA_Map_extension.mjs:712
  importMap@file:///home/user/.config/tiled/extensions/CDDA_Map_extension.mjs:445
  @file:///home/user/.config/tiled/extensions/CDDA_Map_extension.mjs:958
```

I think it's because campsite.json starts with a monstergroup not mapgen

**Comment by solerante** [comment]
> I think it's because campsite.json starts with a monstergroup not mapgen
This is correct, it was looking for the first entry to get the map size. Now it's getting the map size from the first entry that is a json mapgen, which is not great since entries can have different sizes.
Also broken was that the logic to check if there is a palette defined seems broken, and then it starts looking for palettes.
